services:
  ollama-container:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - app_network

  flask-app:
    image: jose/ollama-flask:latest
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - ollama-container
    environment:
      - OLLAMA_URL=http://ollama-container:11434
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  ollama_data:
